services:
  - type: web
    name: meeg-blog-app
    env: node
    plan: starter
    region: frankfurt
    buildCommand: pnpm i; pnpm build
    startCommand: pnpm start
    healthCheckPath: /
    envVars:
      - key: STORYBLOK_TOKEN
        sync: false
